# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('client_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id_type', models.CharField(choices=[('per', 'C\xe9dula F\xedsica'), ('jur', 'C\xe9dula Jur\xeddica'), ('pas', 'Pasaporte')], default='per', max_length=3, verbose_name='Tipo de Identificaci\xf3n')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num Identificaci\xf3n')),
                ('client_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direcci\xf3n')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('client_has_credit', models.BooleanField(default=False, verbose_name='Tiene Cr\xe9dito?')),
                ('client_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='L\xedmite de Cr\xe9dito')),
                ('client_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Saldo')),
                ('client_credit_days', models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='D\xedas de Cr\xe9dito')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_payment_date', models.DateField(verbose_name='Fecha')),
                ('credit_payment_time', models.TimeField(verbose_name='Hora')),
                ('credit_payment_sales', models.ManyToManyField(to='sales.Sale', verbose_name='Facturas')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client_credit_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.CreditPayment', verbose_name='Abonos'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_pending_sales',
            field=models.ManyToManyField(blank=True, null=True, to='sales.Sale', verbose_name='Facturas Pendientes'),
        ),
    ]
