# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='credit_payment_sales',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_credit_payments',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_pending_sales',
        ),
        migrations.DeleteModel(
            name='CreditPayment',
        ),
    ]
