# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayCreditCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=255, verbose_name='Tipo de Tarjeta')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tipo de Tarjeta',
                'verbose_name_plural': 'Tipos de Tarjeta',
            },
        ),
        migrations.CreateModel(
            name='PayCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_currency_name', models.CharField(max_length=255, verbose_name='Moneda')),
                ('pay_currency_sign', models.CharField(max_length=255, verbose_name='S\xedmbolo de Moneda')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='PayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_detail_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Efectivo')),
                ('pay_detail_change', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Vuelto')),
                ('pay_detail_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Credito')),
                ('pay_detail_credit_card', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Tarjeta')),
                ('pay_detail_credit_card_auth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Autorizaci\xf3n')),
                ('pay_detail_check', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Cheque')),
                ('pay_detail_check_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de Cheque')),
                ('pay_detail_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Transferencia')),
                ('pay_detail_transfer_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de Transferencia')),
                ('pay_detail_credit_card_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.PayCreditCardType', verbose_name='Tipo de Tarjeta')),
                ('pay_detail_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.PayCurrency', verbose_name='Moneda')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
            },
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'M\xe9todo de Pago',
                'verbose_name_plural': 'M\xe9todos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Fecha')),
                ('sale_time', models.TimeField(verbose_name='Hora')),
                ('sale_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Saldo Factura')),
                ('sale_type', models.DecimalField(decimal_places=0, default=1, max_digits=1, verbose_name='Tipo de venta')),
                ('sale_iv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='IV')),
                ('sale_disc_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento %')),
                ('sale_disc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Descuento Dinero')),
                ('sale_sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Subtotal')),
                ('sale_total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Total')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_detail_product_id', models.PositiveIntegerField(verbose_name='Id del Art\xedculo')),
                ('sale_detail_product_code', models.PositiveIntegerField(verbose_name='C\xf3digo del Art\xedculo')),
                ('sale_detail_description', models.CharField(max_length=255, verbose_name='Descripci\xf3n del Art\xedculo')),
                ('sale_detail_product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Precio Unitario')),
                ('sale_detail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Cantidad')),
                ('sale_detail_disc_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento %')),
                ('sale_detail_disc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Descuento Dinero')),
                ('sale_detail_iv_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IV %')),
                ('sale_detail_total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Precio Unitario')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sales.SaleDetail', verbose_name='Detalle de la Venta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_pay_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.PayDetail', verbose_name='Detalle de Pago'),
        ),
        migrations.AddField(
            model_name='paydetail',
            name='pay_detail_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.PayMethod', verbose_name='Tipo de Pago'),
        ),
    ]
