# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160914_1540'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_payment_date', models.DateField(verbose_name='Fecha')),
                ('credit_payment_time', models.TimeField(verbose_name='Hora')),
                ('credit_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Monto del Abono')),
                ('credit_payment_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
                ('credit_payment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.PayDetail', verbose_name='Detalles del Pago')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_pending',
            field=models.BooleanField(default=False, verbose_name='Factura Pendiente?'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit_payment_sales',
            field=models.ManyToManyField(to='sales.Sale', verbose_name='Facturas'),
        ),
    ]
