# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160914_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='credit_payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.PayDetail', verbose_name='Detalles del Pago'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='credit_payment_sales',
            field=models.ManyToManyField(blank=True, to='sales.Sale', verbose_name='Facturas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_client',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaleDetail', verbose_name='Detalle de la Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_pay_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.PayDetail', verbose_name='Detalle de Pago'),
        ),
    ]
