# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(default=' ', max_length=255, verbose_name='Descripci\xf3n del producto')),
                ('product_code', models.PositiveIntegerField(default=0, unique=True, verbose_name='C\xf3digo')),
                ('product_barcode', models.PositiveIntegerField(blank=True, default=0, verbose_name='C\xf3digo de Barras')),
                ('product_useinventory', models.BooleanField(default=False, verbose_name='Sistema de Inventarios?')),
                ('product_inventory', models.FloatField(default=0, verbose_name='Existencia en Inventario')),
                ('product_minimum', models.FloatField(default=0, verbose_name='M\xednimo en inventario')),
                ('product_sellmethod', models.CharField(choices=[('uni', 'Por Unidad'), ('bul', 'A Granel'), ('kit', 'En Paquete(kit)')], default='uni', max_length=3, verbose_name='Se Vende Por')),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo \u20a1')),
                ('product_autoprice', models.BooleanField(default=False, verbose_name='Precio Autom\xe1tico?')),
                ('product_utility', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Utilidad %')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio sin Impuestos \u20a1')),
                ('product_usetaxes', models.BooleanField(default=False, verbose_name='Usa Impuestos?')),
                ('product_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Impuestos %')),
                ('product_sellprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta \u20a1')),
            ],
            options={
                'ordering': ['product_code'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productdepartment_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Familia')),
                ('productdepartment_code', models.CharField(max_length=2, unique=True, verbose_name='Identificador de Familia')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='ProductSubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsubdepartment_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Sub-Familia')),
                ('productsubdepartment_code', models.CharField(max_length=2, verbose_name='Identificador de Sub-Familia')),
                ('productsubdepartment_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductDepartment', verbose_name='Familia')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Sub-Familia',
                'verbose_name_plural': 'Sub-Familias',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductDepartment', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subdepartment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductSubDepartment', verbose_name='Sub-Familia'),
        ),
    ]
