# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160914_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subdepartment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubDepartment', verbose_name='Sub-Familia'),
        ),
        migrations.AlterField(
            model_name='productsubdepartment',
            name='product_subdepartment_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia'),
        ),
    ]
